### ISSUE TITLE
[BUG] Players Disappearing When Changing Characters

### ISSUE THREAD

**Issue by LateNightRP** [qbcore-framework/qb-multicharacter#112] opened 2022-05-18 18:20 UTC
**Describe the bug**
We have noticed when you go to your apartment (or house) and change character in-game, and leave apartment (or house) it will put you in a different instance than what everyone else is in. Its acting like when you change character it is not putting you back into the correct instance that everyone is in when you leave apartment (or house).

**To Reproduce**
1. Enter apartment (with other people in server)
2. Change your character
3. Leave apartment with new character you just changed into
4. Meet some at the same location and you will not see them till the person who changed character re-logs 

**Screenshots**
My apologies for not having and video for this. I will try and get video later.

**Questions (please complete the following information):**
 - When you last updated: 5/4/2022
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? No

**Comment by BerkieBb** [comment] 2022-07-14 19:28
1. Wrong resource to put an issue on
2. qb-houses doesn't use routingbuckets, so you can't have an issue with routing buckets in houses
3. The only way you could have this issue with apartments is if an error happened whilst the leaveapartment function was executed on the client side or the server side setinsidemeta event errored.

**Comment by peppinoita** [comment] 2022-07-14 19:59
may be it is related to qb-core itself

**Comment by BerkieBb** [comment] 2022-07-15 09:03
qb-core itself doesn't do anything with it, it has a routing bucket wrapper, but that's only used by qb-apartments, not by the core itself

**Comment by Z3rio** [comment] 2022-08-27 21:00
Closing, invalid / wrong resource to send the issue for. Could not replicate and also just sounds unlikely it would happen.
I would guess this is caused by onesync, qb-core, your artifacts or something else then qb-multicharacter.

**Closed** 2022-08-27 21:22 UTC
Labels: bug
